mit_app/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import MitnadvCreateView,MitnadvDetailView, SnifDetailView, MitnadviListView, SnifListView, SnifCreateView


urlpatterns = [
    path("mit/<int:pk>",MitnadvDetailView.as_view(), name = "mitnadv-detail"),
    path("mit/list",MitnadviListView.as_view(), name = "mitnadvim-list"),
    path("mit/add",MitnadvCreateView.as_view(), name = "mitnadv-create"),
    
    path("snif/<int:pk>",SnifDetailView.as_view(), name = "snif-detail"),
    path("snif/list",SnifListView.as_view(), name = "snifs-list"),
    path("snif/add",SnifCreateView.as_view(), name = "snif-create"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mit_pro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("mit_app.urls")),
]

mit_app/models.py
from django.db import models
import datetime

class Gift(models.Model):
    gift = models.CharField(max_length = 30)
    use = models.BooleanField(default=False)

    def __str__(self):
        return self.gift

class Mitnadv(models.Model):
    
    GENDER = (
        ("M","Male"),
        ("F","Female")
    )

    f_name = models.CharField(max_length = 30)
    l_name = models.CharField(max_length = 30, blank = True, null=True)
    gander = models.CharField(max_length = 1,choices = GENDER, blank = True, null=True)
    age = models.CharField(max_length = 30, blank = True, null=True)

    address = models.CharField(max_length = 100, blank = True, null=True)
    phone = models.CharField(max_length = 100, blank = True, null=True)
    email = models.EmailField(blank = True, null=True)
    image = models.ImageField(upload_to = "upload/" ,blank = True, null=True) 

    snif = models.ForeignKey("Snif", on_delete=models.SET_NULL, null= True)

    money_for_month = models.CharField(max_length = 4)

    time_start = models.TimeField(blank = True, null =True)
    time_end = models.TimeField(blank = True, null =True)

    gifts = models.ManyToManyField(Gift)
    

    def __str__(self):
        return self.f_name
    
    
class Snif(models.Model):
    name = models.CharField(max_length = 20)
    address = models.CharField(max_length = 20)
    image = models.ImageField(upload_to = "upload/",blank = True, null = True)

    def __str__(self):
        return self.name




#    GIFTS = [
#        ("TE","teeth"),
#        ("VE","vacation"),
#        ("CL","clothes"),
#        ("CO","course"),
#    ]
#
#    gift = models.CharField(max_length = 2, choices = GIFTS, default = "CL")

mit_app/views.py
from django.shortcuts import render

from .models import Mitnadv,Snif, Gift

from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic import DetailView

from django.http import HttpResponseRedirect, HttpResponse

from django.db.models import Count

from django.urls import reverse_lazy

from django.core.mail import send_mail



class MitnadvCreateView(CreateView):
    
    model = Mitnadv
    template_name = "mit_app/mitnadv-create.html"
    fields = [
        "f_name",
        "l_name",
        "gander",
        "age",
        "address",
        "phone",
        "email",
        "image",
        "snif",
        "time_start",
        "time_end",
        "gifts",
        "money_for_month"]

    context_object_name = "mit"
    
    def get_success_url(self):
        return reverse_lazy("mitnadv-detail", kwargs={"pk" : self.object.pk})


class MitnadvDetailView(DetailView):
    model = Mitnadv
    template_name = "mit_app/mitnadv-detail.html"
    context_object_name = "mit"


    def post(self ,request, **kwargs):

        obj = Mitnadv.objects.get(pk = kwargs["pk"])
        money_for_month = obj.money_for_month
        num = request.POST.get("num-month",0)
        result = int(money_for_month) * int(num)

        money_for_year =int(money_for_month) * 12

        check_boxs = request.POST.getlist("check")

        content = {
            "money_calc":result,
            "money_for_year":money_for_year ,
            "check_boxs" : check_boxs,
            "mit":obj
            }

        return render(request, "mit_app/mitnadv-detail.html" ,content)

    def get(self, request, *args, **kwargs):

        def get_next_mit():
            next = Mitnadv.objects.filter(pk__gt = kwargs["pk"]).order_by("pk").first()
            return next

        def get_pre_mit():
            pre = Mitnadv.objects.filter(pk__lt = kwargs["pk"]).order_by("pk").last()
            return pre

        next_mit = get_next_mit()
        pre_mit = get_pre_mit()


        obj = Mitnadv.objects.get(pk = kwargs["pk"])
        money_for_month = obj.money_for_month
        money_for_year =int(money_for_month) * 12
        
        content = {
            "money_for_year":money_for_year,
            "next_mit":next_mit,
            "pre_mit":pre_mit,
            "mit":obj,
        }

        return render(request, "mit_app/mitnadv-detail.html" , content)


class MitnadviListView(ListView):

    model = Mitnadv
    context_object_name = "all_mit"
    template_name = "mit_app/mitnadvim-list.html"
    snifs = Snif.objects.all()

    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "all")
        order = self.request.GET.get("orderby", "f_name")
        if filter_val == "all":
            return Mitnadv.objects.all()
        else:
            new_context = Mitnadv.objects.filter(
                snif__name = filter_val
            ).order_by(order)
            return new_context
        
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "all")
        context["orderby"] = self.request.GET.get("orderby", "f_name")
        return context
    

    def get(self, request, *args, **kwargs):

        obj  = self.get_queryset()
        
        def insert_mit_name():
            mitnadvim = obj
            return mitnadvim
        
        def pay_for_all_mitnadvim():
            mitnadvim = insert_mit_name()
            sum = 0 
            for field in mitnadvim.values("money_for_month"):
                sum += int(field["money_for_month"]) 
            return sum
            
        sum_month = pay_for_all_mitnadvim()
        sum_year = sum_month * 12 
        content = {
            "sum_month":sum_month,
            "sum_year":sum_year,
            "snifs":self.snifs,
            "all_mit":obj,
        }
        
        return render(request, "mit_app/mitnadvim-list.html", content)



class SnifCreateView(CreateView):
    
    model = Snif
    template_name = "mit_app/snif-create.html"
    fields = [
        "name",
        "address",
        "image",
    ]

    context_object_name = "snif"
    
    def get_success_url(self):
        return reverse_lazy("snif-detail", kwargs={"pk" : self.object.pk})


class SnifDetailView(DetailView):

    model = Snif
    template_name = "mit_app/snif-detail.html"
    context_object_name = "snif"

    def post(self, request, *args, **kwargs):

        

        def insert_mit_name():
            mitnadv = Mitnadv.objects.all()
            snif = insert_snif()
            mit_names = mitnadv.filter(snif = snif)
            return mit_names

        def insert_snif():
            snif = Snif.objects.get(pk = kwargs["pk"])
            return snif

        def get_list_mail_to_mitnadvim():
            list_mit_mail = []
            mits = insert_mit_name()
            for mit in mits:
                mail = mit.email
                list_mit_mail.append(mail)
            return list_mit_mail

        list_mail_to_mits = get_list_mail_to_mitnadvim()
        snif = insert_snif()
        subject = self.request.POST.get("subject" , 0)
        message = self.request.POST.get("message" , 0)
        if message == "":
            message = "default - nothing to see here, hi mayan :) send from django"

        #send_mail(
        #    subject,
        #    massage,
        #    "yohaido159@gmail.com",
        #    list_mail_to_mits
        #)





        content = {
            "snif":snif,
        }

        return render(request, "mit_app/snif-detail.html", content)


        

        

    def get(self, request, *args,**kwargs):


        def insert_mit_name():
            mitnadv = Mitnadv.objects.all()
            snif = insert_snif()
            mit_names = mitnadv.filter(snif = snif)
            return mit_names

        def insert_snif():
            snif = Snif.objects.get(pk = kwargs["pk"])
            return snif

        def pay_for_all_mitnadvim():
            mitnadvim = insert_mit_name()
            sum = 0 
            for field in mitnadvim.values("money_for_month"):
                sum += int(field["money_for_month"]) 
            return sum
        
        def sum_gift_given():
            mitnadvim = insert_mit_name()
            field_name = "gifts"
            gifts_dic = {}
            sum = 0
            quertset_count = mitnadvim.values(field_name).order_by(field_name).annotate(the_count=Count(field_name))

            for each in quertset_count:
                if each["gifts"] == 1:
                    gift_name = "teeth"
                elif each["gifts"] == 2:
                    gift_name = "vacation"
                elif each["gifts"] == 3:
                    gift_name = "clothes"
                elif each["gifts"] == 4:
                    gift_name = "courses"

                sum += int(each["the_count"])
                
                gifts_dic[gift_name] = each["the_count"]

            return gifts_dic, sum


        def get_next_snif():
            next = Snif.objects.filter(pk__gt = kwargs["pk"]).order_by("pk").first()
            return next

        def get_pre_snif():
            pre = Snif.objects.filter(pk__lt = kwargs["pk"]).order_by("pk").last()
            return pre



        next_snif = get_next_snif()
        pre_snif = get_pre_snif()

        mit_names = insert_mit_name()
        snif = insert_snif()

        sum_for_month = pay_for_all_mitnadvim()    
        sum_for_year = sum_for_month * 12

        gifts_dic, sum_gifts = sum_gift_given()





        content = {
            "mit_names":mit_names,
            "sum_for_month":sum_for_month,
            "sum_for_year":sum_for_year,
            "gifts_dic":gifts_dic,
            "sum_gifts":sum_gifts,
            "pre_snif":pre_snif,
            "next_snif":next_snif,
            "snif":snif,
        }
        return render(request, "mit_app/snif-detail.html", content)
   

class SnifListView(ListView):

    model = Snif
    context_object_name = "all_snifs"
    template_name = "mit_app/snifs-list.html"

    snifs = Snif.objects.all()


    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "all")
        order = self.request.GET.get("orderby", "name")

        if filter_val == "all":
            return Snif.objects.all()
        else:
            new_context = Snif.objects.filter(
                name = filter_val
            ).order_by(order)
            return new_context
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "all")
        context["orderby"] = self.request.GET.get("orderby", "name")
        return context
    

    def get(self, request, *args, **kwargs):
        

        def mitnadvim_in_snif():
            snifs = Snif.objects.all()
            mit_dict = {}

            for snif in snifs:
                mits = snif.mitnadv_set.all()
                mit_dict[snif.name] = mits
            return mit_dict
        
        mit_dict = mitnadvim_in_snif()

        obj  = self.get_queryset()
        
        content = {
            "snifs":self.snifs,
            "mit_dict":mit_dict,
            "all_snifs":obj,
        }
        
        return render(request, "mit_app/snifs-list.html", content)

mit_app/templates/mit_app/mitnadv-create.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>mitnadv</title>
  </head>
  <body>
    <h1>create mitnadv</h1>
    <form action="" method="POST">
      <p>{{ form.as_p }}</p>
      {% csrf_token %}
    </form>

  </body>
</html>

mit_app/templates/mit_app/mitnadv-detail.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>mitnadv</title>
  </head>
  <body>
    <div>
      <h2>detail mitnadv</h2>
      <p>f_name: {{ mit.f_name }}</p>
      <p>l_name: {{ mit.l_name }}</p>
      <p>gander: {{ mit.get_gander_display }}</p>
      <p>age: {{ mit.age }}</p>
      <p>phone: {{ mit.phone }}</p>
      <p>address: {{ mit.address }}</p>
      <p>email: {{ mit.email }}</p>
      <p>time start: {{ mit.time_start }}</p>

      <p>
        image: <img src="{{ mit.image.url }}" alt="" height="50" width="auto" />
      </p>
    </div>
    <br />
    <h2>other</h2>
    <div>
      <p>snif: {{ mit.snif }}</p>
      <p>money_m: {{ mit.money_for_month }}</p>

      <h2>time</h2>
      <p>time start {{ mit.time_start }}</p>
      <p>time end {{ mit.time_end }}</p>

      <h2>pay for x mounth</h2>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="number" name="num-month" />
        <input type="submit" value="submit" />
      </form>

      <p>{{ money_calc }}</p>

      <h2>pay for year</h2>
      <p>{{ money_for_year }}</p>

      <h2>Gifts to use</h2>
      <form method="POST">
        {% for gift in mit.gifts.all %}

        <input type="checkbox" name="check" value="{{ gift }}" />

        {{ gift }}
        
        <br />

        {% endfor %}
        <input type="submit" />
        {% csrf_token %}
      </form>

      <h3>mitnadv use:</h3>
      {% for check in check_boxs %} {% if None %} false {% endif %}

      <p>{{ check }}</p>

      {% endfor %}

      <h3>next or pre mit</h3>
      {% if pre_mit %}
      <a><a href="/mit/{{pre_mit.pk}}">pre</a></a>
      {% endif %}

      {% if next_mit %}
      <a><a href="/mit/{{next_mit.pk}}">next</a></a>
      {% endif %}

      <h3>back to list</h3>
      <a href="{% url 'mitnadvim-list' %}">to list</a>

    </div>
  </body>
</html>

mit_app/templates/mit_app/mitnadvim-list.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>mitnadv</title>
    <style>
      div {
        border: solid 1px;
        max-width: 200px;
      }
    </style>
  </head>
  <body>
    {% for mit in all_mit %}
      
    <div>
      <h3><a href="/mit/{{mit.id}}">name:{{mit.f_name}} </a></h3>
      <img src="{{mit.image.url}}" alt="" height="100" width="auto">
      <br>
      <a href="/snif/{{mit.snif.id}}">snif: {{mit.snif}}</a>
    </div>
    <br>
    {% endfor %}

    <div>
      <h2>pay for mounth for all:</h2> <p> {{sum_month}}</p>
      <h2>pay for mounth for year: </h2> <p>{{sum_year}}</p>
    </div>

    <form action="{% url 'mitnadvim-list' %}" method="GET"> 
      <select name="filter">
        <option value="all">all</option>
        {% for snif in snifs  %}
        <option value="{{snif.name}}" >{{snif.name}}</option>
        {% endfor %}
      </select>
      <input type="submit" value="submit">
    </form>

    <h3>add mitnadv</h3>
    <a href="{% url 'mitnadv-create'%}">add</a>



  </body>
</html>

mit_app/templates/mit_app/snif-create.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>mitnadv</title>
  </head>
  <body>
    <h1>create snif</h1>
    <form action="" method="POST" enctype="multipart/form-data">
      <p>{{ form.as_p }}</p>
      {% csrf_token %}
      <input type="submit" value="submit">
    </form>

  </body>
</html>

mit_app/templates/mit_app/snif-detail.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>mitnadv</title>
    <style>
      table,
      th,
      td {
        border: solid 1px black;
      }
    </style>
  </head>
  <body>
    <h1>snif detail</h1>
    <p>{{ snif.name }}</p>
    <p>{{ snif.address }}</p>
    <p><img src="{{ snif.image.url }}" alt="" height="300" width="auto" /></p>

    <h2>mitnadvim</h2>
    {% for mit in mit_names %}
    {{ mit.f_name }}
    <br />
    {% endfor %}

    <h2>sum for month</h2>
    {{ sum_for_month }}
    <br /><br />
    <h2>sum for year</h2>
    {{ sum_for_year }}

    <h2>sum gift to be given</h2>
    <table>
      <tr>
        <th>gift</th>
        <th>sum</th>
      </tr>
      {% for key, value in gifts_dic.items %}
      <tr>
        <td>{{ key }}</td>
        <td>{{ value }}</td>
      </tr>
      {% endfor %}
      <tr>
        <td>sum: </td>
        <td>{{sum_gifts}} </td>
      </tr>
    </table>

    <h3>next or pre snif</h3>
    {% if pre_snif %}
    <a><a href="/snif/{{pre_snif.pk}}">pre</a></a>
    {% endif %}

    {% if next_snif %}
    <a><a href="/snif/{{next_snif.pk}}">next</a></a>
    {% endif %}

    <h3>back to list</h3>
    <a href="{% url 'snifs-list' %}">to list</a>

          <h3>send sms and mail</h3>

      <form method="POST">
        <input type="text" name="subject">
        <br>
            <textarea name="message" cols="30" rows="10"></textarea>
            <input type="submit" value="sumbit">
            {% csrf_token %}
      </form>    
      
      {% comment %}
send_mail(

  'subject',
   'body of the message',
    'yohaido159@gmail.com',
     ['yohai159951@gmail.com',]
  )


{% endcomment %}
  </body>
</html>

mit_app/templates/mit_app/snifs-list.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>mitnadv</title>
    <style>
      div {
        border: solid 1px;
        max-width: 200px;
      }
    </style>
  </head>
  <body>
    {% for snif in all_snifs %}
      
    <div>
      <h3><a href="/snif/{{snif.id}}">name:{{snif.name}}</a>   </h3>
      <img src="{{snif.image.url}}" alt="" height="100" width="auto">
      <p>mitnadvim:</p>
      {% for key, value in mit_dict.items %}
        {% if key == snif.name %} 
          {% for mit in value %}
           <a href="/mit/{{mit.id}}"><p>{{mit.f_name}}</p></a>

          {% endfor %}
        {% endif %}
      {% endfor %}
      </div>
    <br>
    {% endfor %}

    <form action="{% url 'snifs-list' %}" method="GET"> 
      <select name="filter">
        <option value="all">all</option>
        {% for snif in snifs  %}
        <option value="{{snif.name}}" >{{snif.name}}</option>
        {% endfor %}

      </select>
      <input type="submit" value="submit">
    </form>

    <h3>add snif</h3>
    <a href="{% url 'snif-create'%}">add</a>



  </body>
</html>